### ISSUE TITLE
Wrong networking settings in local docker-compose

### ISSUE THREAD

**Issue by hlogeon** [JincorTech/backend-ico-dashboard#189]
For some reason I can't start project without removing networking settings. And when I was changing `docker-compose.yml` for the 4th time in one month I thought that may be for local development we don't even need this configurations.

Consider moving network settings to another `docker-compose` or just removing it from docker-compose.

**Comment by hlogeon** [comment]
@Aleserche @ddevilbb do you use this settings in local environment?
```
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.0.0/16
          gateway: 10.100.0.1
```
and static IP binding in container settings.


As far as I remember this was used to be able to pass this IP addresses to throttler and tenant whitelists. But I think we can just pass`*` for local development and it supposed to work well.
